linters:
  BorderZero:
    enabled: false

  CapitalizationInSelector:
    enabled: false

  ColorKeyword:
    enabled: true

  Comment:
    enabled: false

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: true

  EmptyRule:
    enabled: true

  HexFormat:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: false
    width: 2

  LeadingZero:
    enabled: true

  NameFormat:
    enabled: true
    convention: BEM

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: true
    extra_properties:
      - text-size-adjust
      - _width

  UnnecessaryParentReference:
    enabled: false

  SelectorDepth:
    enabled: true
    max_depth: 5

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  SpaceBetweenParens:
    enabled: true

  StringQuotes:
    enabled: true
    style: double_quotes

  TrailingSemicolon:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true
